### ISSUE TITLE
Fails to build with hyprwayland-scanner >= 0.4.3

### ISSUE THREAD

**Issue by jbeich** [hyprwm/hyprpicker#102]
```c++
src/hyprpicker.cpp:576:66: error: unknown type name 'wl_resource'
  576 |     m_pPointer->setEnter([this](CCWlPointer* r, uint32_t serial, wl_resource* surface, wl_fixed_t surface_x, wl_fixed_t surface_y) {
      |                                                                  ^
src/hyprpicker.cpp:576:26: error: no viable conversion from '(lambda at src/hyprpicker.cpp:576:26)' to 'std::function<void (CCWlPointer *, uint32_t, wl_proxy *, wl_fixed_t, wl_fixed_t)>' (aka 'function<void (CCWlPointer *, unsigned int, wl_proxy *, int, int)>')
  576 |     m_pPointer->setEnter([this](CCWlPointer* r, uint32_t serial, wl_resource* surface, wl_fixed_t surface_x, wl_fixed_t surface_y) {
      |                          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  577 |         auto x = wl_fixed_to_double(surface_x);
      |         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  578 |         auto y = wl_fixed_to_double(surface_y);
      |         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  579 |
  580 |         m_vLastCoords = {x, y};
      |         ~~~~~~~~~~~~~~~~~~~~~~~
  581 |
  582 |         markDirty();
      |         ~~~~~~~~~~~~
  583 |
  584 |         for (auto& ls : m_vLayerSurfaces) {
      |         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  585 |             if (ls->pSurface->resource() == surface) {
      |             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  586 |                 m_pLastSurface = ls.get();
      |                 ~~~~~~~~~~~~~~~~~~~~~~~~~~
  587 |                 break;
      |                 ~~~~~~
  588 |             }
      |             ~
  589 |         }
      |         ~
  590 |
  591 |         m_pCursorShapeDevice->sendSetShape(serial, WP_CURSOR_SHAPE_DEVICE_V1_SHAPE_CROSSHAIR);
      |         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/include/c++/v1/__functional/function.h:856:47: note: candidate constructor not viable: no known conversion from '(lambda at src/hyprpicker.cpp:576:26)' to 'nullptr_t' (aka 'std::nullptr_t') for 1st argument
  856 |   _LIBCPP_HIDE_FROM_ABI _LIBCPP_HIDE_FROM_ABI function(nullptr_t) _NOEXCEPT {}
      |                                               ^        ~~~~~~~~~
/usr/include/c++/v1/__functional/function.h:857:25: note: candidate constructor not viable: no known conversion from '(lambda at src/hyprpicker.cpp:576:26)' to 'const function<void (CCWlPointer *, unsigned int, wl_proxy *, int, int)> &' for 1st argument
  857 |   _LIBCPP_HIDE_FROM_ABI function(const function&);
      |                         ^        ~~~~~~~~~~~~~~~
/usr/include/c++/v1/__functional/function.h:858:25: note: candidate constructor not viable: no known conversion from '(lambda at src/hyprpicker.cpp:576:26)' to 'function<void (CCWlPointer *, unsigned int, wl_proxy *, int, int)> &&' for 1st argument
  858 |   _LIBCPP_HIDE_FROM_ABI function(function&&) _NOEXCEPT;
      |                         ^        ~~~~~~~~~~
/usr/include/c++/v1/__functional/function.h:860:25: note: candidate template ignored: requirement '__callable<(lambda at src/hyprpicker.cpp:576:26) &, false>::value' was not satisfied [with _Fp = (lambda at src/hyprpicker.cpp:576:26)]
  860 |   _LIBCPP_HIDE_FROM_ABI function(_Fp);
      |                         ^
./protocols/wayland.hpp:1038:86: note: passing argument to parameter 'handler' here
 1038 |     void setEnter(F<void(CCWlPointer*, uint32_t, wl_proxy*, wl_fixed_t, wl_fixed_t)> handler);
      |                                                                                      ^
src/hyprpicker.cpp:593:66: error: unknown type name 'wl_resource'
  593 |     m_pPointer->setLeave([this](CCWlPointer* r, uint32_t timeMs, wl_resource* surf) {
      |                                                                  ^
src/hyprpicker.cpp:593:26: error: no viable conversion from '(lambda at src/hyprpicker.cpp:593:26)' to 'std::function<void (CCWlPointer *, uint32_t, wl_proxy *)>' (aka 'function<void (CCWlPointer *, unsigned int, wl_proxy *)>')
  593 |     m_pPointer->setLeave([this](CCWlPointer* r, uint32_t timeMs, wl_resource* surf) {
      |                          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  594 |         for (auto& ls : m_vLayerSurfaces) {
      |         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  595 |             if (ls->pSurface->resource() == surf) {
      |             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  596 |                 renderSurface(ls.get(), true);
      |                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  597 |             }
      |             ~
  598 |         }
      |         ~
  599 |     });
      |     ~
/usr/include/c++/v1/__functional/function.h:856:47: note: candidate constructor not viable: no known conversion from '(lambda at src/hyprpicker.cpp:593:26)' to 'nullptr_t' (aka 'std::nullptr_t') for 1st argument
  856 |   _LIBCPP_HIDE_FROM_ABI _LIBCPP_HIDE_FROM_ABI function(nullptr_t) _NOEXCEPT {}
      |                                               ^        ~~~~~~~~~
/usr/include/c++/v1/__functional/function.h:857:25: note: candidate constructor not viable: no known conversion from '(lambda at src/hyprpicker.cpp:593:26)' to 'const function<void (CCWlPointer *, unsigned int, wl_proxy *)> &' for 1st argument
  857 |   _LIBCPP_HIDE_FROM_ABI function(const function&);
      |                         ^        ~~~~~~~~~~~~~~~
/usr/include/c++/v1/__functional/function.h:858:25: note: candidate constructor not viable: no known conversion from '(lambda at src/hyprpicker.cpp:593:26)' to 'function<void (CCWlPointer *, unsigned int, wl_proxy *)> &&' for 1st argument
  858 |   _LIBCPP_HIDE_FROM_ABI function(function&&) _NOEXCEPT;
      |                         ^        ~~~~~~~~~~
/usr/include/c++/v1/__functional/function.h:860:25: note: candidate template ignored: requirement '__callable<(lambda at src/hyprpicker.cpp:593:26) &, false>::value' was not satisfied [with _Fp = (lambda at src/hyprpicker.cpp:593:26)]
  860 |   _LIBCPP_HIDE_FROM_ABI function(_Fp);
      |                         ^
./protocols/wayland.hpp:1039:62: note: passing argument to parameter 'handler' here
 1039 |     void setLeave(F<void(CCWlPointer*, uint32_t, wl_proxy*)> handler);
      |                                                              ^
4 errors generated.
```

**Comment by vaxerski** [comment]
oopsie
